function units = transfunits(v)
  units = v.units;
  for k = 1 : numel(v.units)
    [units(k).x, units(k).y] = transfdata(v.units(k), ...
    point(v.marks(v.units(k).a).dim, 0), ...
    point(v.marks(v.units(k).b).dim, 0), ...
    v.backbone(v.units(k).a), ...
    v.backbone(v.units(k).b));
  end
end
