function t = tunnel(p)
  z = num2cell(zeros(1, numel(p)));
  t = struct('x', {p.x}, 'y', {p.y}, 's', {p.s}, ...
  'dl', z, 'dr', z, ...
  'xl', {p.x}, 'yl', {p.y}, ...
  'xr', {p.x}, 'yr', {p.y});
end
