function v = vehicle(vdata)
  backbone = pointpath(vdata.marks.dim, zeros(size(vdata.marks)));
  v = struct(...
  'marks', vdata.marks, ...
  'units', vdata.units, ...
  'backbone', backbone, ...
  'tunits', vdata.units);
end
